# Travis configuration
language: Python

python:
    - 2.7

# whitelist
branches:
    only:
        - master

install:
    - pip install -r requirements.txt

scripts:
    - ./runAnalyse.sh
    - ./runTests.sh

notifications:
    email:
        recipients:
           - thomas.lehmann.private@gmail.com
        on_success: always
        on_failure: always
