# Travis configuration
language: python

python:
    - "2.7"

# whitelist
branches:
    only:
        - master

before_install:
    - sudo apt-get update -qq
    - pip --version

install:
    - sudo apt-get install -qq sloccount
    - pip install -r requirements.txt

scripts:
    - ./runAnalyse.sh
    - ./runTests.sh

notifications:
    email:
        recipients:
           - thomas.lehmann.private@gmail.com
        on_success: always
        on_failure: always
