# Travis configuration
language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"

# whitelist
branches:
    only:
        - master

before_install:
    - sudo apt-get update -qq
    - docker version

install:
    - sudo apt-get install -qq sloccount
    - python -V
    - pip -V
    - pip install coveralls tox-travis

script: tox

after_success:
    - coveralls

notifications:
    email:
        recipients:
           - thomas.lehmann.private@gmail.com
        on_success: always
        on_failure: always
